### ISSUE TITLE
Better error handling for incorrect values in settings

### ISSUE THREAD

**Issue by sharkmu** [pixelbracket/formatto#11]
If you add a value in the settings which is greater than 0, but not a round number, then it'll still accept it. 
The problem with it is that it isn't possible to add 1.5 gap or some sort.

My fix for this problem is to check the values not just to be greater than 0, but also for it to be a round number. Although a second solution could be to round up those numbers. 

Let me know which solution is the better.

**Note:** I'd like to work on this Issue, if possible

**Comment by ghost** [comment]
I think it's better to show a warning message. It'd be less confusing.
