### ISSUE TITLE
No values in Settings gives an error

### ISSUE THREAD

**Issue by sharkmu** [pixelbracket/formatto#13]
If my settings are all deleted like this:
![settings](https://github.com/decaplanet/formatto/assets/65612124/3b555856-a155-4236-8f9b-67dddedf93a3)
Then this Notice shows up:
![error](https://github.com/decaplanet/formatto/assets/65612124/873814cb-7094-4125-a984-b762131fe7de)

It'd also be great to work in these conditions with the default values.

**Note:** I would like to work on this issue, also please add a `bug` label to it.

**Comment by ghost** [comment]
<img width="623" alt="image" src="https://github.com/polyecho/formatto/assets/160427240/0fcab460-8fa7-4969-8fec-fde68c4bcc59">

Just like this image, I think those options can be empty by default. What do you think?

**Comment by ghost** [comment]
If you don't mind, I'll try implementing this myself.

**Comment by sharkmu** [comment]
> If you don't mind, I'll try implementing this myself.

Alright, no problem

**Comment by ghost** [comment]
Feature implemented in commit [0427919](https://github.com/polyecho/formatto/commit/042791966d8a036d2610549ced6280bd43a76409).
