### ISSUE TITLE
Unexpected input cursor behavior

### ISSUE THREAD

**Issue by ghost** [pixelbracket/formatto#14]
Because [the cursor location stays the same](https://github.com/decaplanet/formatto/blob/1e793740988131bc6009d35f97e91fb63c93423f/src/utils.ts#L14C9-L14C51), it sometimes casues unexpected behaviors.

<div>
    <img alt="before" width="49.4%" src="https://github.com/decaplanet/formatto/assets/126875757/4ce3f96d-20a4-43fa-a314-1fc655a20971">
    <img alt="after" width="49.4%"src="https://github.com/decaplanet/formatto/assets/126875757/b69c4459-71f5-47a0-9b48-865b82fb8403">
</div>

**Comment by sharkmu** [comment]
Perhaps adding an option to always move the cursor to the beginning of the document could be a solution for the problem.

**Comment by ghost** [comment]
I'm thinking about making it remember the line number before the run. The problem is, I'm still trying to figure out how I'm going to put the cursor in the line for the same text. Feel free to tell me if anyone have a suggestion.

**Comment by ghost** [comment]
@sharkmu Wouldn't that be more confusing than the original way?

**Comment by sharkmu** [comment]
> @sharkmu Wouldn't that be more confusing than the original way?

I mean it could be an additional setting (feature)

**Comment by evasquare** [comment]
The feature can be an improvement but I don't think it's necessary at this moment. I'm closing the issue.
