### ISSUE TITLE
It occasionally generates duplicate headings due to alternate heading parsing

### ISSUE THREAD

**Issue by ghost** [pixelbracket/formatto#20]
### What version of the plugin are you having the issue with?

1.2.2

### Issue description

![video](https://github.com/polyecho/formatto/assets/160427240/77327120-1e73-4b00-8dbc-86b39312dedc)
Possibly because of the way the plugin handles alternate heading syntax, it sometimes creates another duplicate heading.

## How to reproduce the issue
To reproduce this issue, try formatting this example input.

```md
## Dynamic Arrays (ex: Python `list`)
- 
```

You'll get the following output:
```md
## Dynamic Arrays (ex: Python `list`)



## Dynamic Arrays (ex: Python `list`)
-
```

**Comment by polyecho** [comment]
Pull request #21 merged.

**Comment by ghost** [comment]
Pull request https://github.com/polyecho/formatto/pull/21 merged.
