### ISSUE TITLE
Formatto gives error when parse a note with a separator '---'

### ISSUE THREAD

**Issue by DHERRADOR** [pixelbracket/formatto#22]
### What version of the plugin are you having the issue with?

1.2.3

### Issue description

If you have a note with one or several separators, I mean to write three hyphens '---', formatto can't parse it correctly and gives an error in that line.

**Comment by ghost** [comment]
Can you provide an example input? I'd like to try it myself.

**Comment by ghost** [comment]
I think I handled this issue with the [Release 1.2.4](https://github.com/polyecho/formatto/releases/tag/1.2.4). Feel free to reopen the issue if this doesn't work. Thanks for the bug report!

**Comment by DHERRADOR** [comment]
Hi, I couldn’t send it to you because I saw that it doesn’t fail in all situations. So I was waiting to find a case where it fails. In any case thanks for your soon answer. I hope you have fixed the bug. BREl 31 mar 2024, a las 19:31, Echo ***@***.***> escribió:﻿
Can you provide an example input? I'd like to try it myself.
