### ISSUE TITLE
[More Feature] Study Case: Copy text from facebook comment

### ISSUE THREAD

**Issue by 3xploiton3** [pixelbracket/formatto#29]
i copy text from facebook comment
![image](https://github.com/user-attachments/assets/d62ef09a-fb6b-4cc3-b7e0-8fbf7b003e6d)

Paste to obsidian
![image](https://github.com/user-attachments/assets/8ae8e358-48b3-43f0-b58c-c0cbad128bae)

our expect
![image](https://github.com/user-attachments/assets/604c4de6-9753-4943-8d4f-961fcae5a117)

could you add some feature for this case ?

**Comment by evasquare** [comment]
Unfortunately, that's not what Formatto was made for. But you can try pasting as plain text.

<img width="287" alt="image" src="https://github.com/user-attachments/assets/639898e4-3873-4b8a-b8fa-d540f057cb8a">

Here are some keyboard shortcuts.
Windows: ctrl + shift + v
macOS: cmd + shift + v (or cmd + option + shift + v)

Hope this helps!
