### ISSUE TITLE
Clearing text after a code block with spaces before ```

### ISSUE THREAD

**Issue by AKuntysh** [pixelbracket/formatto#4]
Thanks for the useful plugin, but plugin removes everything after a code block with a space before  ```. 

For example

SPACE\```
code
\```

or 

\```
code
SPACE\```

**Comment by ghost** [comment]
Thanks! I'll take a look right away.

**Comment by ghost** [comment]
Just added a validity check in commit [f77d3bf](https://github.com/decaplanet/formatto/commit/f77d3bf195b70a47e0ae6b970b539948dff1e46c)! You can try it in [version 1.0.8](https://github.com/decaplanet/formatto/releases/tag/1.0.8).
Thanks. :)
