### ISSUE TITLE
Docs, update README, contribution guide

### ISSUE THREAD

**Issue by sharkmu** [pixelbracket/formatto#8]
## What is this Issue about?
I think it'd be great to have more **guides** on how to contribute, maybe a **detailed docs** about the code.

**Comment by ghost** [comment]
Making templates for issues and pull requests would be great. I'll write them later soon. Thanks for the suggestion!

**Comment by ghost** [comment]
Just added some issue templates. [53962a2](https://github.com/decaplanet/formatto/commit/53962a264dead264d3b0a7ee15c45a95300790a6)

**Comment by ghost** [comment]
I was going to add a pull request template, but I think it's fine without the template. I'll close the issue.
